### ISSUE TITLE
Combine ZephyrApp with Bluetooth Gist

### ISSUE THREAD

**Issue by ppasler** [darkopetrovic/ZephyrApp#1]
Hi Darko,

I know you haven't worked lately in this project, but I am trying to get the App to work and hope you can help me. I am working on a project at university and need the Bioharness data in real-time via bluetooth. Is this even possible with the app?

First of all, there are serveral compatibility issues:
- QT -> use Signal instead of SIGNAL, new click events and so on
- Serial -> it does not accept Integer ports on Windows
  These are things I can handle and change where it's needed.

I am still not quite sure how the original Zephyr lib fetches data - via Bluetooth or must the Bioharness be in the docking station? I am not very familiar with Bluetooth and serial connections, but I found your Gist (https://gist.github.com/darkopetrovic/2127217) and got that to work. What I need is a little example how to fetch data in real-time from the device and get encoded data (maybe a map).

I'm thankful even for little tips!
Regards,
paul

**Comment by darkopetrovic** [comment]
Hi ppasler, 

I'm very sorry for the delay I've completly forgetten this message. Did you manage to get someting with the App? 

As I remember there was some change in Qt with the Signal becoming SIGNAL. Previously I used Signal and changed to SIGNAL with the last version at that time. 

With Bioharness Bluetooth, when the driver is properly installed, you'll see an serial port on the OS. Therefore it is not required for the device to be in the docking station. You communicate wirelessly via the serial port directly.

The code to communicate and initilize the BioHarness can be found in `device_zephyr.py`. Let me now if you still have problem to see the real-time data from the device. 

BR.

**Comment by ppasler** [comment]
Hi Darko,

thanks for your answer. I managed to fix the `PyQT` and `Serial` updates. 

My problem is to conect to the serial port (which is not part of your app, I know). I posted a question on [stackoverflow](http://stackoverflow.com/questions/40340341/how-to-establish-serial-connection-with-bluetooth-device-on-win7), but didn't receive a helpful answer - except your Gist. It seems my device can't be detected with my Win7. If I run the TestApplication from Zephyr it works and your Gist is also able to connect (with the manual inserted MAC adress). 

I wondered if it is hard to combine your Gist and the App to directly connect via BT?

Greetz paul

**Comment by darkopetrovic** [comment]
Ok I see. Normally it is more easier to use the created virtual COM port. I used the serial port because the zephyr library require one. 

You say on stackoverflow that you have the COM port related to your Bluetooth in the device manager? Have you tried on a desktop with a Bluetooth dongle? That's what I use. 

I you have a COM port with your Bluetooth, try this:

- Configure your BioHarness (while in the docking station) with the provided software to send data periodically. 
- And test this script:

```python
import serial
ser = serial.Serial('COMX') # replace X with the port number
ser.read(100) 
```
Normally you should be able to read some data which means that your bluetooth serial port is working. 

- And then try to send data to see if you still block in the function:

```python
ser.write(b'hello')
```

If you want to use the Bluetooth socket instead, you have to make some change in the zephyr library in the `protocol.py` file and some adjustement in my App. It's not hard, but I recommend you to make the serial port working :)

Perhaps try to update you Bluetooth driver on your laptop and have a working [Serial Port Profile](https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Serial_Port_Profile_.28SPP.29) with your bluetooth.

**Comment by ppasler** [comment]
Hey Darko,

thanks for your suggestions.

`ser.read(100)` and `ser.write(b'hello')` do block both.

As the device cannot be found from the windows device manager, I assume the handshake does not take place and the serial connection is not established... I am not familiar with bluetooth and serial connections, maybe I am missing an option within my OS

I tried it on Linux (same Laptop) and got a timeout for `read`, but the serial connection was established the bluetooth led was on.

So I think I'll have to integrate the direct bluetooth connection.

**Comment by ppasler** [comment]
Hi Darko,

I made some changes (not everything  works so far) for latest serial and pyqt4:
https://github.com/ppasler/ZephyrApp/tree/feature-pyqt4-compatibility

Regards,
paul

**Comment by darkopetrovic** [comment]
Hello Paul,

> I made some changes (not everything works so far) for latest serial and pyqt4:

what is working?

What COM port did you used to test the connection if it is not found in the windows device manager? Do you have something like this in your Device Manager: 

![zephyr](https://cloud.githubusercontent.com/assets/1554288/21307643/c3977546-c5d6-11e6-80fd-ef64617ff092.png)

Have a look equally at the chapter 6.2.2 of this document if you haven't already done so:

http://www.zephyr-technology.nl/downloads/getDownload/id/97 

> Some PC platforms may have native Bluetooth supported by non-Windows driver files, or a user may
> have a Bluetooth USB dongle previously installed, which uses non-Windows driver files (e.g.
> Broadcomm). If this is the case, then existing driver files must be uninstalled, or a different USB dongle
> used.

If you can afford to buy an USB dongle and have the Windows driver version 6.1.xxxx being used you'll save a lot of time instead of trying to patch the application to work with a direct bluetooth connection. 

BR,
Darko

**Comment by ppasler** [comment]
Hi Darko,

the App starts without QT errors, some blocks are diabled :)
The Bioharness is far away from working...

Ich checked with your screenshots and I have the same COM-port on my machine (also same driver file version). 
I've already read the chapter, but I have a MS driver, so this couldn't be the problem in my eyes.

As I can find the device with Linux (on the same Laptop), the bluetooth device itself couldn't be the problem? But I'll give the dongle approach a try.

Thanks again,
paul
